name: NDFA
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - dglteam
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch=1.10.0
  - torchvision
  - torchaudio
  - dgl
  - python-rocksdb
  - pip
  - pip:
      - -r requirements.cpu.txt
