name: NDFA
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - pyg
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch=1.10.0
  - pyg
  - torch-scatter
  - torch-sparse
  - torchvision
  - torchaudio
  - python-rocksdb
  - pip
  - pip:
      - -r file:requirements.cpu.txt
