name: NDFA
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - dglteam
dependencies:
  - python=3.9
  - numpy
  - scipy
  - cudatoolkit=11.3
  - pytorch=1.10.0
  - torchvision
  - torchaudio
  - dgl-cuda11.1
  - python-rocksdb
  - pip
  - pip:
      - -r requirements.cuda.txt
