name: NDFA
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - dglteam
dependencies:
  - python=%PYTHON_VERSION%
  - numpy
  - scipy
  - cudatoolkit=%CUDA_VERSION%
  - pytorch=%PYTORCH_VERSION%
  - torchvision
  - torchaudio
  - dgl-cuda%CUDA_VERSION%
  - python-rocksdb
  - pip
  - pip:
      - -r requirements.txt
